export const mockPhotos = [
  {
    _id: "1",
    projectId: "q7Mx2Lp9Va1Nz4Kc8TdR",
    imageUrl: "/homepage-img1.jpg",
    altText: "Home Page Image 1",
  },
  {
    _id: "2",
    projectId: "b3Rw8Hj6Ye2Pm5Xs1UkQ",
    imageUrl: "/homepage-img2.jpg",
    altText: "Home Page Image 2",
  },
  {
    _id: "3",
    projectId: "m9Cv4Ta7Lo3Qp8Wd2FnJ",
    imageUrl: "/homepage-img3.jpg",
    altText: "Home Page Image 3",
  },
  {
    _id: "4",
    projectId: "z1Nk6Uy5Re4Gh7Bm9XpL",
    imageUrl: "/homepage-img4.jpg",
    altText: "Home Page Image 4",
  },
  {
    _id: "5",
    projectId: "d8Fs3Qa1Wi6Tv0Jk5YeM",
    imageUrl: "/homepage-img5.jpg",
    altText: "Home Page Image 5",
  },
  {
    _id: "6",
    projectId: "p4Lg9Xc2Mn7Rb1Hs6ZaT",
    imageUrl: "/homepage-img6.jpg",
    altText: "Home Page Image 6",
  },
  {
    _id: "7",
    projectId: "t6Hq1Vz8Ke3Yw5Nc4JuP",
    imageUrl: "/homepage-img7.jpg",
    altText: "Home Page Image 7",
  },
  {
    _id: "8",
    projectId: "y2Bd7Mp4Sa9Xk6Fr1LoV",
    imageUrl: "/homepage-img8.jpg",
    altText: "Home Page Image 8",
  },
  {
    _id: "9",
    projectId: "k5Wr0Jn3Tu8Qe2Zx7CiN",
    imageUrl: "/homepage-img9.jpg",
    altText: "Home Page Image 9",
  },
  {
    _id: "10",
    projectId: "n8Px6Lf1Go4Vm9Hy3RaK",
    imageUrl: "/homepage-img10.jpg",
    altText: "Home Page Image 10",
  },
  {
    _id: "11",
    projectId: "r3Ty9Qm5Ub2Xn7Ce4WsJ",
    imageUrl: "/homepage-img11.jpg",
    altText: "Home Page Image 11",
  },
  {
    _id: "12",
    projectId: "v1Za4Kd8Pi6Lt0Mq5HxR",
    imageUrl: "/homepage-img12.jpg",
    altText: "Home Page Image 12",
  },
  {
    _id: "13",
    projectId: "h7Cu2Xe9Ro1Wk4Sb8JnF",
    imageUrl: "/homepage-img13.jpg",
    altText: "Home Page Image 13",
  },
  {
    _id: "14",
    projectId: "x4Nm8Qa3Yi7Pv1Lg6TdC",
    imageUrl: "/homepage-img14.jpg",
    altText: "Home Page Image 14",
  },
  {
    _id: "15",
    projectId: "j9Re5Tk2Vo6Xs4Hb1QmW",
    imageUrl: "/homepage-img15.jpg",
    altText: "Home Page Image 15",
  },
  {
    _id: "16",
    projectId: "c2Lp7Yu1Zn5Mf8Kq3GwT",
    imageUrl: "/homepage-img16.jpg",
    altText: "Home Page Image 16",
  },
  {
    _id: "17",
    projectId: "w6Hs4Bj9Qa2Vr7Xe1NuK",
    imageUrl: "/homepage-img17.jpg",
    altText: "Home Page Image 17",
  },
  {
    _id: "18",
    projectId: "f1Gt8Mx3Lo5Zp2Rc9YvH",
    imageUrl: "/homepage-img18.jpg",
    altText: "Home Page Image 18",
  },
  {
    _id: "19",
    projectId: "u5Kq2Wd7Ti1Yn4Pb8XsL",
    imageUrl: "/homepage-img19.jpg",
    altText: "Home Page Image 19",
  },
  {
    _id: "20",
    projectId: "s8Vn3Hr6Je9Qm2Lc5XaP",
    imageUrl: "/homepage-img20.jpg",
    altText: "Home Page Image 20",
  },
  {
    _id: "21",
    projectId: "l4Xc1Pf8Ru3Tk6Zm9HbQ",
    imageUrl: "/homepage-img21.jpg",
    altText: "Home Page Image 21",
  },
  {
    _id: "22",
    projectId: "g7Mq5Ys2Va8Ln1De4KwR",
    imageUrl: "/homepage-img22.jpg",
    altText: "Home Page Image 22",
  },
  {
    _id: "23",
    projectId: "a9Tb4Xh6Po2Wr7Jk1CvN",
    imageUrl: "/homepage-img23.jpg",
    altText: "Home Page Image 23",
  },
  {
    _id: "24",
    projectId: "e3Ju8Qn5Zi1Ms4Ly7TdK",
    imageUrl: "/homepage-img24.jpg",
    altText: "Home Page Image 24",
  },
  {
    _id: "25",
    projectId: "o6Yp2Lc9Hg4Vx1Rb8WmS",
    imageUrl: "/homepage-img25.jpg",
    altText: "Home Page Image 25",
  },
];

export const archiveData = [
  {
    _id: "1",
    title: "Jully Issue",
    image: "/jully-issue.jpg",
    stackImages: ["/jully-issue-2.jpg", "/jully-issue-3.jpg"],
    year: 2022,
  },
  {
    _id: "2",
    title: "House of Eda",
    image: "/house-of-eda.jpg",
    stackImages: ["/jully-issue-2.jpg", "/jully-issue-3.jpg"],
    year: 2022,
  },
  {
    _id: "3",
    title: "Dhruv Kapoor",
    image: "/dhruv-kapoor.jpg",
    stackImages: ["/jully-issue-2.jpg", "/jully-issue-3.jpg"],
    year: 2023,
  },
  {
    _id: "4",
    title: "Roqa",
    image: "/roqa.jpg",
    stackImages: ["/jully-issue-2.jpg", "/jully-issue-3.jpg"],
    year: 2024,
  },
  {
    _id: "5",
    title: "Estrella",
    image: "/estrella.jpg",
    stackImages: ["/jully-issue-2.jpg", "/jully-issue-3.jpg"],
    year: 2024,
  },
  {
    _id: "6",
    title: "Gauri & Nainika",
    image: "/gauri-and-nainika.jpg",
    stackImages: ["/jully-issue-2.jpg", "/jully-issue-3.jpg"],
    year: 2025,
  },
  {
    _id: "7",
    title: "Preeti Kler",
    image: "/preeti-kler.jpg",
    stackImages: ["/jully-issue-2.jpg", "/jully-issue-3.jpg"],
    year: 2025,
  },
  {
    _id: "8",
    title: "Libas",
    image: "/libas.jpg",
    stackImages: ["/jully-issue-2.jpg", "/jully-issue-3.jpg"],
    year: 2026,
  },
];
