/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/extract.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  landingIntro: string;
  aboutBio: string;
  collaborationNote: string;
  aboutImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  aboutImageAlt: string;
  instagramUrl?: string;
  twitterUrl?: string;
  email?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type ClientReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "client";
};

export type WorkCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "workCategory";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  client: ClientReference;
  shootTitle?: string;
  shootMonth:
    | "january"
    | "february"
    | "march"
    | "april"
    | "may"
    | "june"
    | "july"
    | "august"
    | "september"
    | "october"
    | "november"
    | "december";
  shootYear: number;
  slug: Slug;
  category: WorkCategoryReference;
  credits?: Array<string>;
  instagramUrl?: string;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  coverAlt: string;
  gallery: Array<
    {
      _key: string;
    } & ProjectImage
  >;
  order?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type ProjectImage = {
  _type: "projectImage";
  mediaType: "image" | "video";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  video?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  alt?: string;
};

export type Client = {
  _id: string;
  _type: "client";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
};

export type WorkCategory = {
  _id: string;
  _type: "workCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  order: number;
  isVisible?: boolean;
  previewImages: Array<{
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    alt: string;
    _type: "previewImage";
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | AboutPage
  | SanityImageCrop
  | SanityImageHotspot
  | ClientReference
  | WorkCategoryReference
  | Project
  | Slug
  | SanityFileAssetReference
  | ProjectImage
  | Client
  | WorkCategory
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: WORK_CATEGORIES_QUERY
// Query: *[_type == "workCategory" && isVisible == true]    | order(order asc, title asc) {      _id,      title,      "slug": slug.current,      order,      "previewImages": previewImages[0...4] {        alt,        "url": image.asset->url,        "width": image.asset->metadata.dimensions.width,        "height": image.asset->metadata.dimensions.height,        "blurDataURL": image.asset->metadata.lqip      }    }
export type WORK_CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  order: number;
  previewImages: Array<{
    alt: string;
    url: string | null;
    width: number | null;
    height: number | null;
    blurDataURL: string | null;
  }>;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: PROJECT_BY_SLUG_QUERY
// Query: *[_type == "project" && slug.current == $slug][0] {    _id,    "slug": slug.current,    "category": category->title,    shootMonth,    shootYear,    "client": client->name,    instagramUrl,    credits,    shootTitle,    gallery[] {      mediaType,      "image": image.asset-> {        url,        "width": metadata.dimensions.width,        "height": metadata.dimensions.height,        "blurDataURL": metadata.lqip      },      "video": video.asset->url,      alt    }  }
export type PROJECT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  slug: string;
  category: string;
  shootMonth:
    | "april"
    | "august"
    | "december"
    | "february"
    | "january"
    | "july"
    | "june"
    | "march"
    | "may"
    | "november"
    | "october"
    | "september";
  shootYear: number;
  client: string;
  instagramUrl: string | null;
  credits: Array<string> | null;
  shootTitle: string | null;
  gallery: Array<{
    mediaType: "image" | "video";
    image: {
      url: string;
      width: number | null;
      height: number | null;
      blurDataURL: string | null;
    } | null;
    video: string | null;
    alt: string | null;
  }>;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: PROJECTS_BY_CATEGORY_QUERY
// Query: *[_type == "project" && category->slug.current == $category] | order(order asc, _createdAt desc) {    _id,    "projectId": slug.current,    "imageUrl": coverImage.asset->url,    "altText": coverAlt  }
export type PROJECTS_BY_CATEGORY_QUERY_RESULT = Array<{
  _id: string;
  projectId: string;
  imageUrl: string | null;
  altText: string;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: ABOUT_PAGE_QUERY
// Query: *[_type == "aboutPage"][0] {    landingIntro,    aboutBio,    collaborationNote,    "aboutImage": aboutImage.asset-> {      url,      "width": metadata.dimensions.width,      "height": metadata.dimensions.height,      "blurDataURL": metadata.lqip    },    aboutImageAlt,    instagramUrl,    twitterUrl,    email  }
export type ABOUT_PAGE_QUERY_RESULT = {
  landingIntro: string;
  aboutBio: string;
  collaborationNote: string;
  aboutImage: {
    url: string;
    width: number | null;
    height: number | null;
    blurDataURL: string | null;
  } | null;
  aboutImageAlt: string;
  instagramUrl: string | null;
  twitterUrl: string | null;
  email: string | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "workCategory" && isVisible == true]\n    | order(order asc, title asc) {\n      _id,\n      title,\n      "slug": slug.current,\n      order,\n      "previewImages": previewImages[0...4] {\n        alt,\n        "url": image.asset->url,\n        "width": image.asset->metadata.dimensions.width,\n        "height": image.asset->metadata.dimensions.height,\n        "blurDataURL": image.asset->metadata.lqip\n      }\n    }\n': WORK_CATEGORIES_QUERY_RESULT;
    '\n  *[_type == "project" && slug.current == $slug][0] {\n    _id,\n    "slug": slug.current,\n    "category": category->title,\n    shootMonth,\n    shootYear,\n    "client": client->name,\n    instagramUrl,\n    credits,\n    shootTitle,\n    gallery[] {\n      mediaType,\n      "image": image.asset-> {\n        url,\n        "width": metadata.dimensions.width,\n        "height": metadata.dimensions.height,\n        "blurDataURL": metadata.lqip\n      },\n      "video": video.asset->url,\n      alt\n    }\n  }\n': PROJECT_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "project" && category->slug.current == $category] | order(order asc, _createdAt desc) {\n    _id,\n    "projectId": slug.current,\n    "imageUrl": coverImage.asset->url,\n    "altText": coverAlt\n  }\n': PROJECTS_BY_CATEGORY_QUERY_RESULT;
    '\n  *[_type == "aboutPage"][0] {\n    landingIntro,\n    aboutBio,\n    collaborationNote,\n    "aboutImage": aboutImage.asset-> {\n      url,\n      "width": metadata.dimensions.width,\n      "height": metadata.dimensions.height,\n      "blurDataURL": metadata.lqip\n    },\n    aboutImageAlt,\n    instagramUrl,\n    twitterUrl,\n    email\n  }\n': ABOUT_PAGE_QUERY_RESULT;
  }
}
